// <auto-generated />
namespace DoctorOnlineBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newDoctorDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newDoctorDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201911291045129_newDoctorDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
